// Generated by CoffeeScript 2.4.1
var counter, draw, setup;

counter = 0;

setup = function() {
  createCanvas(200, 200);
  button('Up', () => {
    return counter++;
  });
  button('Down', () => {
    return counter--;
  });
  
  // button 'Down', (=> counter--),
  // 	position:'absolute'
  // 	left:'200px'
  // 	top:'50px'
  // 	width:'100px'
  // 	color: '#ff0'
  // 	backgroundColor: 'black'
  // 	fontSize: '200%'
  textAlign(CENTER, CENTER);
  textSize(100);
  return fc(1, 0, 0);
};

draw = function() {
  bg(0);
  return text(counter, 100, 100);
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsT0FBQSxFQUFBLElBQUEsRUFBQTs7QUFBQSxPQUFBLEdBQVU7O0FBRVYsS0FBQSxHQUFRLFFBQUEsQ0FBQSxDQUFBO0VBQ1AsWUFBQSxDQUFhLEdBQWIsRUFBaUIsR0FBakI7RUFFQSxNQUFBLENBQU8sSUFBUCxFQUFhLENBQUEsQ0FBQSxHQUFBO1dBQUcsT0FBQTtFQUFILENBQWI7RUFDQSxNQUFBLENBQU8sTUFBUCxFQUFlLENBQUEsQ0FBQSxHQUFBO1dBQUcsT0FBQTtFQUFILENBQWYsRUFIQTs7Ozs7Ozs7OztFQWNBLFNBQUEsQ0FBVSxNQUFWLEVBQWlCLE1BQWpCO0VBQ0EsUUFBQSxDQUFTLEdBQVQ7U0FDQSxFQUFBLENBQUcsQ0FBSCxFQUFLLENBQUwsRUFBTyxDQUFQO0FBakJPOztBQW1CUixJQUFBLEdBQU8sUUFBQSxDQUFBLENBQUE7RUFDTixFQUFBLENBQUcsQ0FBSDtTQUNBLElBQUEsQ0FBSyxPQUFMLEVBQWEsR0FBYixFQUFpQixHQUFqQjtBQUZNIiwic291cmNlc0NvbnRlbnQiOlsiY291bnRlciA9IDBcclxuXHJcbnNldHVwID0gLT5cclxuXHRjcmVhdGVDYW52YXMgMjAwLDIwMFxyXG5cclxuXHRidXR0b24gJ1VwJywgPT4gY291bnRlcisrXHJcblx0YnV0dG9uICdEb3duJywgPT4gY291bnRlci0tXHJcblx0XHJcblx0IyBidXR0b24gJ0Rvd24nLCAoPT4gY291bnRlci0tKSxcclxuXHQjIFx0cG9zaXRpb246J2Fic29sdXRlJ1xyXG5cdCMgXHRsZWZ0OicyMDBweCdcclxuXHQjIFx0dG9wOic1MHB4J1xyXG5cdCMgXHR3aWR0aDonMTAwcHgnXHJcblx0IyBcdGNvbG9yOiAnI2ZmMCdcclxuXHQjIFx0YmFja2dyb3VuZENvbG9yOiAnYmxhY2snXHJcblx0IyBcdGZvbnRTaXplOiAnMjAwJSdcclxuXHRcclxuXHR0ZXh0QWxpZ24gQ0VOVEVSLENFTlRFUlxyXG5cdHRleHRTaXplIDEwMFxyXG5cdGZjIDEsMCwwXHJcblxyXG5kcmF3ID0gLT5cclxuXHRiZyAwXHJcblx0dGV4dCBjb3VudGVyLDEwMCwxMDBcclxuIl19
//# sourceURL=c:\github\p5Dojo2\ID_Counter\coffee\sketch.coffee