// Generated by CoffeeScript 2.4.1
var draw, mousePressed, setup, state;

state = {
  x: 100,
  y: 100
};

setup = function() {
  return createCanvas(200, 200);
};

draw = function() {
  var i, j, k, len, ref, results, x, y;
  bg(0);
  sc(1);
  ref = range(40);
  results = [];
  for (k = 0, len = ref.length; k < len; k++) {
    i = ref[k];
    results.push((function() {
      var l, len1, ref1, results1;
      ref1 = range(4);
      results1 = [];
      for (l = 0, len1 = ref1.length; l < len1; l++) {
        j = ref1[l];
        [x, y] = [0, i * 5, 200, 200 - i * 5, 0].slice(j, +(j + 1) + 1 || 9e9);
        results1.push(line(state.x, state.y, x, y));
      }
      return results1;
    })());
  }
  return results;
};

mousePressed = function(event) {
  return [state.x, state.y] = [event.x, event.y];
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsSUFBQSxFQUFBLFlBQUEsRUFBQSxLQUFBLEVBQUE7O0FBQUEsS0FBQSxHQUFRO0VBQUEsQ0FBQSxFQUFFLEdBQUY7RUFBTyxDQUFBLEVBQUU7QUFBVDs7QUFFUixLQUFBLEdBQVEsUUFBQSxDQUFBLENBQUE7U0FBRyxZQUFBLENBQWEsR0FBYixFQUFpQixHQUFqQjtBQUFIOztBQUVSLElBQUEsR0FBTyxRQUFBLENBQUEsQ0FBQTtBQUNOLE1BQUEsQ0FBQSxFQUFBLENBQUEsRUFBQSxDQUFBLEVBQUEsR0FBQSxFQUFBLEdBQUEsRUFBQSxPQUFBLEVBQUEsQ0FBQSxFQUFBO0VBQUEsRUFBQSxDQUFHLENBQUg7RUFDQSxFQUFBLENBQUcsQ0FBSDtBQUNBO0FBQUE7RUFBQSxLQUFBLHFDQUFBOzs7O0FBQ0M7QUFBQTtNQUFBLEtBQUEsd0NBQUE7O1FBQ0MsQ0FBQyxDQUFELEVBQUcsQ0FBSCxDQUFBLEdBQVEsQ0FBQyxDQUFELEVBQUcsQ0FBQSxHQUFFLENBQUwsRUFBTyxHQUFQLEVBQVcsR0FBQSxHQUFJLENBQUEsR0FBRSxDQUFqQixFQUFtQixDQUFuQixDQUFzQjtzQkFDOUIsSUFBQSxDQUFLLEtBQUssQ0FBQyxDQUFYLEVBQWEsS0FBSyxDQUFDLENBQW5CLEVBQXFCLENBQXJCLEVBQXVCLENBQXZCO01BRkQsQ0FBQTs7O0VBREQsQ0FBQTs7QUFITTs7QUFRUCxZQUFBLEdBQWUsUUFBQSxDQUFDLEtBQUQsQ0FBQTtTQUFXLENBQUMsS0FBSyxDQUFDLENBQVAsRUFBUyxLQUFLLENBQUMsQ0FBZixDQUFBLEdBQW9CLENBQUMsS0FBSyxDQUFDLENBQVAsRUFBUyxLQUFLLENBQUMsQ0FBZjtBQUEvQiIsInNvdXJjZXNDb250ZW50IjpbInN0YXRlID0geDoxMDAsIHk6MTAwXHJcblxyXG5zZXR1cCA9IC0+IGNyZWF0ZUNhbnZhcyAyMDAsMjAwXHJcblxyXG5kcmF3ID0gLT5cclxuXHRiZyAwXHJcblx0c2MgMVxyXG5cdGZvciBpIGluIHJhbmdlIDQwXHJcblx0XHRmb3IgaiBpbiByYW5nZSA0XHJcblx0XHRcdFt4LHldID0gWzAsaSo1LDIwMCwyMDAtaSo1LDBdW2ouLmorMV1cclxuXHRcdFx0bGluZSBzdGF0ZS54LHN0YXRlLnkseCx5XHJcblxyXG5tb3VzZVByZXNzZWQgPSAoZXZlbnQpIC0+IFtzdGF0ZS54LHN0YXRlLnldID0gW2V2ZW50LngsZXZlbnQueV1cclxuIl19
//# sourceURL=c:\Lab\2019\116-Moire\coffee\sketch.coffee